version: "3.9"

services:
  mysql:
    image: mysql:latest
    platform: linux/arm64
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      TZ: "Asia/Tokyo"
    volumes:
      - mysql-test:/var/lib/mysql
volumes:
  mysql-test:
