name: Linter
on: [pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: node_modules cache
        run: |
          rm -rf node_modules/
      - uses: actions/checkout@v3
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          eslint_flags: "src/**/*.{ts,tsx}"
          fail_on_error: true # 指摘が発生したらjobを失敗扱いにする
