name: Formatter
on: [pull_request]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          ref: ${{ github.head_ref }}
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.{ts,tsx,js,jsx,json}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Run Prettier
        run: |
          npm ci
          npx prettier --write ${{ env.GIT_DIFF_FILTERED }} # 環境変数GIT_DIFF_FILTEREDに差分のあるファイルが列挙されている
        if: env.GIT_DIFF
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Prettier Change
